# author: G K. Snow
# date: Friday, 23 June 2023 8:52:04 PM
# Config version: v1.0
stages:
  - Test-ScriptFileInfo # dependancies
  - Build-PSModule # Build the Module 
  - Build-NuPkg # Build NuPkG File Using NuPSForge Module
  - Deploy-GitlabPackageRepo # deploy to psgallary
  - Mirror-to-Microsoft.PSGallary # deploy to psgallary
  - Build-MakeRelease # Build Release
  - Copy-Build-To-GoogleDrive # Copy Build To Google Drive

# -----------------------------------------------
# ScriptFileInfo JOB - run Test-ScriptFileInfo 
# -----------------------------------------------
Test-ScriptFileInfo-job:
  stage: Test-ScriptFileInfo
  script:
    - pwsh.exe
    - Test-ScriptFileInfo -Path .\PSMPacker.ps1

Build-PSModule-job:
  stage: Build-PSModule
  script:
    - pwsh.exe
    - .\build.ps1
  rules:
    - if: '$CI_JOB_NAME == "Test-ScriptFileInfo-job"'
      when: on_success
# -----------------------------------------------
# Build-NuPkg JOB - run Build-NuPkg module
# -----------------------------------------------
Build-NuPkg-job:
  stage: Build-NuPkg
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"























# -----------------------------------------------
# BUILD JOB - BUILD PowerShell Module For Release
# -----------------------------------------------
Build-PSModule-job:
  stage: Build-PSModule
  script:
    - pwsh
    - write-host -f green "Running -> Build-PSModule-job"
    - export CI_COMMIT_MESSAGE="$(git log --format=%B -n 1)"
  rules:
    - if: '$CI_JOB_NAME == "Test-PSSCriptA-job"'
      when: on_success
    - exists:
        - $CI_COMMIT_MESSAGE
    - exists:
        - "$CI_COMMIT_MESSAGE | grep -E (smver: Major|smver: Minor|smver: Patch)"
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always

Test-Cmdlet-job:
  stage: Test-Cmdlet-Functions
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"

Build-NuPkg:
  stage: Build-NuPkg
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"
    
Deploy-GitlabPackageRepo:
  stage: Deploy-GitlabPackageRepo
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"
    
Mirror-to-Microsoft-PSGallary-job:
  stage: Mirror-to-Microsoft-PSGallary
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"

Copy-Build-To-GoogleDrive-job:
  stage: Mirror-to-Microsoft-PSGallary
  script:
    - pwsh.exe
    - write-host -f green "template ci\cd config successfull"